'use client';

import { useEffect, useMemo, useState } from 'react';
import { Check, Circle, Filter, Save } from 'lucide-react';
import { createClient } from '../../lib/supabase/browser';

type Student = { id: string; order_no: number; student_code: string; full_name: string; platoon: number; squad: number };
type FeeMonth = { id: string; label: string; month_order: number; due_year: number | null };
type Payment = { student_id: string; fee_month_id: string; paid: boolean; note: string | null };

const thaiDigits = '๐๑๒๓๔๕๖๗๘๙';
const thai = (value: number) => String(value).replace(/\d/g, (digit) => thaiDigits[Number(digit)]);

export function FeeView() {
  const [students, setStudents] = useState<Student[]>([]); const [months, setMonths] = useState<FeeMonth[]>([]); const [payments, setPayments] = useState<Payment[]>([]); const [group, setGroup] = useState('ทั้งหมด'); const [query, setQuery] = useState(''); const [staff, setStaff] = useState(false); const [message, setMessage] = useState('');
  async function load() { const client = createClient(); const [{ data: studentData }, { data: monthData }, { data: paymentData }] = await Promise.all([client.from('students').select('id,order_no,student_code,full_name,platoon,squad').order('order_no'), client.from('fee_months').select('id,label,month_order,due_year').order('month_order'), client.from('fee_payments').select('student_id,fee_month_id,paid,note')]); setStudents((studentData ?? []) as Student[]); setMonths((monthData ?? []) as FeeMonth[]); setPayments((paymentData ?? []) as Payment[]); }
  useEffect(() => { load(); const client = createClient(); client.auth.getUser().then(async ({ data }) => { if (!data.user) return; const { data: profile } = await client.from('profiles').select('role').eq('id', data.user.id).maybeSingle(); setStaff(profile?.role === 'staff'); }); }, []);
  const visibleStudents = useMemo(() => students.filter((student) => (group === 'ทั้งหมด' || `${student.platoon}/${student.squad}` === group) && `${student.full_name} ${student.student_code}`.toLowerCase().includes(query.toLowerCase())), [group, query, students]);
  const paid = (studentId: string, monthId: string) => payments.find((payment) => payment.student_id === studentId && payment.fee_month_id === monthId)?.paid ?? false;
  const monthRate = (monthId: string) => { if (!students.length) return 0; return Math.round((students.filter((student) => paid(student.id, monthId)).length / students.length) * 100); };
  async function toggle(studentId: string, monthId: string) { if (!staff) return; const next = !paid(studentId, monthId); const { error } = await createClient().from('fee_payments').upsert({ student_id: studentId, fee_month_id: monthId, paid: next, paid_at: next ? new Date().toISOString() : null }, { onConflict: 'student_id,fee_month_id' }); setMessage(error?.message || 'อัปเดตสถานะแล้ว'); if (!error) load(); }
  return <div className="space-y-5"><div className="panel flex flex-col gap-3 p-4 md:flex-row"><input value={query} onChange={(event) => setQuery(event.target.value)} className="control" placeholder="ค้นหาชื่อหรือรหัส" /><select value={group} onChange={(event) => setGroup(event.target.value)} className="control md:max-w-52"><option>ทั้งหมด</option>{[1, 2, 3, 4].flatMap((platoon) => [1, 2, 3, 4, 5].map((squad) => <option key={`${platoon}/${squad}`} value={`${platoon}/${squad}`}>หมวด {platoon} / หมู่ {squad}</option>))}</select><span className="inline-flex items-center gap-2 text-sm text-navy/60"><Filter size={16} /> {staff ? 'staff: คลิกช่องเพื่อบันทึก' : 'โหมดดูอย่างเดียว'}</span></div><div className="panel overflow-x-auto"><table className="min-w-[1150px] w-full border-collapse text-sm"><thead><tr className="bg-navy text-white"><th rowSpan={2} className="border p-2">ลำดับ</th><th rowSpan={2} className="border p-2">รหัส นสต.</th><th rowSpan={2} className="border p-2 text-left">ยศ ชื่อ - สกุล</th><th rowSpan={2} className="border p-2">หมวด / หมู่</th>{months.map((month) => <th key={month.id} className="border p-2 text-center">{month.label}</th>)}</tr><tr className="bg-pine text-white">{months.map((month) => <th key={month.id} className="border p-1 text-xs">จ่าย {monthRate(month.id)}%</th>)}</tr></thead><tbody>{visibleStudents.map((student) => <tr key={student.id} className="hover:bg-gold/10"><td className="border p-2 text-center font-semibold">{thai(student.order_no)}</td><td className="border p-2 text-center">{student.student_code}</td><td className="border p-2 font-semibold">{student.full_name}</td><td className="border p-2 text-center">{thai(student.platoon)} / {thai(student.squad)}</td>{months.map((month) => { const isPaid = paid(student.id, month.id); return <td key={month.id} className={`border p-1 text-center ${isPaid ? 'bg-emerald-50 text-emerald-700' : 'bg-red-50/60 text-red-700'}`}><button type="button" disabled={!staff} onClick={() => toggle(student.id, month.id)} aria-label={`${student.full_name} ${month.label} ${isPaid ? 'ชำระแล้ว' : 'ยังไม่ชำระ'}`} className="mx-auto block rounded p-2 disabled:cursor-default">{isPaid ? <Check size={19} /> : <Circle size={17} />}</button></td>; })}</tr>)}</tbody></table>{!visibleStudents.length && <p className="p-8 text-center text-navy/60">ยังไม่มีรายชื่อในฐานข้อมูล</p>}</div>{message && <p className="inline-flex items-center gap-2 text-sm text-pine"><Save size={16} /> {message}</p>}<div className="flex flex-wrap gap-4 text-xs text-navy/65"><span className="inline-flex items-center gap-1"><Check size={14} className="text-emerald-700" /> ชำระแล้ว</span><span className="inline-flex items-center gap-1"><Circle size={13} className="text-red-700" /> ยังไม่ชำระ</span></div></div>;
}
