'use client';

import { useEffect, useState } from 'react';
import { ShieldCheck } from 'lucide-react';
import { createClient } from '../../lib/supabase/browser';

type Profile = { id: string; full_name: string | null; role: 'member' | 'staff' };

export default function StaffPage() {
  const [profiles, setProfiles] = useState<Profile[]>([]); const [message, setMessage] = useState(''); const [navigation, setNavigation] = useState<Record<string, boolean>>({});
  async function load() { const { data, error } = await createClient().from('profiles').select('id,full_name,role').order('created_at'); if (error) setMessage(error.message); else setProfiles((data ?? []) as Profile[]); }
  useEffect(() => { load(); createClient().from('site_settings').select('value').eq('key', 'navigation').maybeSingle().then(({ data }) => setNavigation((data?.value as Record<string, boolean>) || {})); }, []);
  async function promote(id: string, role: Profile['role']) { const { error } = await createClient().from('profiles').update({ role }).eq('id', id); setMessage(error ? error.message : 'อัปเดตสิทธิ์แล้ว'); if (!error) load(); }
  const menuItems = [['roster', 'ทำเนียบรุ่น'], ['bmi', 'สุขภาพ'], ['fees', 'ค่ากรรมการ'], ['duty', 'ตารางเวร'], ['countdown', 'นับถอยหลัง'], ['readiness', 'เตรียมการณ์'], ['announcements', 'ประกาศ'], ['gallery', 'แกลเลอรี่'], ['wall-of-fame', 'เกียรติยศ'], ['raffle', 'สุ่มรายชื่อ']];
  async function saveNavigation() { const { error } = await createClient().from('site_settings').upsert({ key: 'navigation', value: navigation }, { onConflict: 'key' }); setMessage(error?.message || 'บันทึกการแสดงเมนูแล้ว'); }
  return <main className="min-h-screen px-4 py-8 md:px-8"><div className="mx-auto max-w-5xl"><header className="mb-6 border-l-4 border-gold pl-4"><p className="text-xs font-bold uppercase tracking-[0.25em] text-gold">STAFF CONSOLE</p><h1 className="mt-1 text-3xl font-bold text-navy">จัดการผู้ใช้และการแสดงผล</h1><p className="mt-1 text-navy/65">เฉพาะ staff ที่ผ่าน RLS เท่านั้นจึงจะเปลี่ยนสิทธิ์และเมนูได้</p></header><section className="panel mb-6 p-5"><h2 className="section-title">เมนูที่ต้องการแสดง</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{menuItems.map(([key, label]) => <label key={key} className="flex items-center justify-between rounded-lg border border-navy/10 p-3"><span>{label}</span><input type="checkbox" checked={navigation[key] !== false} onChange={(event) => setNavigation({ ...navigation, [key]: event.target.checked })} /></label>)}</div><button onClick={saveNavigation} className="button-primary mt-4">บันทึกการแสดงผล</button></section><div className="panel overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-navy text-white"><tr><th className="p-3">ชื่อ</th><th className="p-3">สิทธิ์</th><th className="p-3">การจัดการ</th></tr></thead><tbody>{profiles.map((profile) => <tr key={profile.id} className="border-b"><td className="p-3 font-semibold">{profile.full_name || 'ไม่ระบุชื่อ'}</td><td className="p-3">{profile.role}</td><td className="p-3"><button onClick={() => promote(profile.id, profile.role === 'staff' ? 'member' : 'staff')} className="inline-flex items-center gap-2 text-navy underline"><ShieldCheck size={16} /> {profile.role === 'staff' ? 'ลดเป็น member' : 'เลื่อนเป็น staff'}</button></td></tr>)}</tbody></table></div>{message && <p className="mt-4 text-sm text-navy/70">{message}</p>}</div></main>;
}